# Dashboards {.unnumbered}

## Overview
While aboard *R/V Falkor (too)* real-time data is viewable via a variety of [grafana dashboards](http://10.23.9.24/?orgId=1).  

- For an overview of real-time data related to the [*Falkor (too)*](http://10.23.9.24/d/oaTjHQK4z/expedition-overview?orgId=1)

- For an overview of real-time data from [*ROV SuBastian*](http://10.23.9.24/d/fcvJZ9A4k/subastian-overview?orgId=1&refresh=10s)

## Quick-Facts
- Dashboards are set to show recent time periods. Each dashboard may show a different amount of time. The time span can be controlled for viewing in the upper right-hand side. When adjusted, the window for graphs will adjust. Some dashboards have been given the ability to bucket data based on a window choice. This dropdown, if available is in the upper left corner. 
Note: Some calculations are for set time frames and are unaffected by this choice

- Dashboards can be accessed by direct link

## Dashboards of interest
- [*Falkor (too)* Expedition Overview](http://10.23.9.24/d/oaTjHQK4z/expedition-overview?orgId=1)
-  [*ROV SuBastian* Dive Overview](http://10.23.9.24/d/fcvJZ9A4k/subastian-overview?orgId=1&refresh=10s)
- [Meteorlogical Sensors](http://10.23.9.24/d/g9f-EFRVk/falkor-weather?orgId=1&refresh=5s)
- [Underway Seatwer Sensors](http://10.23.9.24/d/g9f-EFRVk/falkor-weather?orgId=1&refresh=5s)
- [USBL](http://10.23.9.24/d/8B6U3t_Vk/usbl-overview?orgId=1)
- [R/V *Falkor (too)* Navigation](http://10.23.9.24/d/eqFYOwK4k/falkor-nav?orgId=1&refresh=5s)




