# Sealog {.unnumbered}

R/V Falkor (too)

## Overview

Sealog is a smart event logger. *R/V Falkor (too)* has two instances aboard the ship. One instance is used for the ship, its underway systems, and tracking of general information related to deployments on instruments. The second instance logs *ROV SuBastian* dives, coupling key metadata (such as video framegrabs, vehicle position, vehicle depth, water temperature, etc.) with each event. Sealog can be configured for each cruise to better support a science party's specific data logging needs. Data, information, and reports captured and generated by Sealog are made available to the science party shortly after a dive.

## Accesiblity

Currently, Sealog can only be reached while onboard the ship, but a cloud-based instance, Seacloud, is made available to scientists after their cruise.

-   Sealog-FKt can be found either at 10.23.11.25/sealog-fkt/ in any web browser, or you can use the “Sealog-Falkor” link at 10.23.11.25.
-   Sealog-Sub can be found either at 10.23.11.25/sealog-sub/ in any web browser, or you can use the “Sealog-Subastian” link at 10.23.11.25.

## Preperation

Prior to an expedition, it is valuable to review the information in this documentation. Once aboard, the science party will be able to work with the Marine Technicaians to adjust Sealog's output within the documented parameters to achieve their data logging and reporting needs.

### Additional Documentation

-   [Sealog-FKt](sealog_falkortoo.qmd)
-   [Sealog-SuB](sealog_subastian.qmd)